#!/bin/bash
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

apt-get install python3 graphviz librsvg2-bin plotutils antlr3

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"

(cd $DIR/../lib/scruffy-master/ && python3 setup.py install)
(cd $DIR/../lib/Python3/ && python3 setup.py install)

