#!/bin/bash
sudo apt-get install python3 graphviz librsvg2-bin plotutils antlr3

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )"

(cd $DIR/../lib/scruffy-master/ && sudo python3 setup.py install)
(cd $DIR/../lib/Python3/ && sudo python3 setup.py install)

