import ast

def createSample(rep):
  #rep = Representation()
  intrn = ast.AccessModifier()
  publ = ast.AccessModifier()
  publ.setPublic()
  priv = ast.AccessModifier()
  priv.setPrivate()
  prot = ast.AccessModifier()
  prot.setProtected()
  void = ast.Type("Void")
  
  basicFunctions = ast.File("BasicFunctions")
  rep.addFile(basicFunctions)
  
  breathing = ast.Namespace("Breathing")
  basicFunctions.addNamespace(breathing)
  
  breath = ast.Iface("Breath")
  breathing.addInterface(breath)
  lungs = ast.Type("Lungs")
  lungsA = ast.Attr("lungs",lungs,priv)
  breath.addAttribute(lungsA)
  respire = ast.Method("respire",void,priv)
  breath.addMethod(respire)

  eating = ast.Namespace("Eating")
  basicFunctions.addNamespace(eating)
  eat = ast.Iface("Eat")
  eating.addInterface(eat)
  mouth = ast.Type("Mouth")
  mouthA = ast.Attr("mouth",mouth,prot)
  energy = ast.Type("Energy")
  consume = ast.Method("consume",energy,priv)
  meal = ast.Type("Meal")
  food = ast.Parameter(meal,"food")
  consume.addParameter(food)
  eat.addMethod(consume)
  eat.addAttribute(mouthA)
  body = ast.Type("Body")
  bodyA = ast.Attr("body",body,prot)
  eat.addAttribute(bodyA)

  
  liveFunctions = ast.File("LiveFunctions")
  rep.addFile(liveFunctions)
  usingBreathing = ast.Using("Breathing")
  liveFunctions.addUsing(usingBreathing)
  usingEating = ast.Using("Eating")
  liveFunctions.addUsing(usingEating)
  living = ast.Namespace("Living")
  
  liveFunctions.addNamespace(living)
  live = ast.Iface("Live")
  living.addInterface(live)
  breathT = ast.Type("Breath")
  eatT = ast.Type("Eat")
  live.addExtend(breathT)
  live.addExtend(eatT)
  exist = ast.Method("exist",void,priv)
  live.addMethod(exist)

  
  biteFile = ast.File("Bite")
  rep.addFile(biteFile)
  biteNamespace = ast.Namespace("Bite")
  biteFile.addNamespace(biteNamespace);
  bite = ast.Iface("Bite")
  biteNamespace.addInterface(bite)
  teeth = ast.Type("Teeth")
  teethA = ast.Attr("teeth",teeth,priv)
  bite.addAttribute(teethA)
  hurt = ast.Type("Hurt")
  attack = ast.Method("attack",hurt,prot)
  attack.isAbstract(True)
  bite.addMethod(attack)

  familiarFile = ast.File("Familiar")
  rep.addFile(familiarFile)
  familiar = ast.Iface("Familiar")
  familarNamespace = ast.Namespace("Familiar")
  familiarFile.addNamespace(familarNamespace)
  familarNamespace.addInterface(familiar)
  cares = ast.Method("cares",void,intrn)
  cares.isAbstract(True)
  familiar.addMethod(cares)

  animalFile = ast.File("Animal")
  rep.addFile(animalFile)
  usingLiving = ast.Using("Living")
  
  animalFile.addUsing(usingLiving)
  animal = ast.Cl("Animal")
  animalFile.addClass(animal)
  bone = ast.Type("Bone")
  boneA = ast.Attr("bone",bone,publ)
  animal.addAttribute(boneA)
  liveT = ast.Type("Live")
  animal.addImplement(liveT)
  move = ast.Method("move",void,prot)
  animal.addMethod(move)
  animal.isAbstract(True)

  
  petFile = ast.File("Pet")
  petNamespace = ast.Namespace("Pet")
  familiarNT = ast.Using("Familiar")
  petNamespace.addUsing(familiarNT)
  petFile.addNamespace(petNamespace)
  rep.addFile(petFile)
  animalT = ast.Type("Animal")
  
  pet = ast.Cl("Pet")
  petNamespace.addClass(pet)
  pet.setExtend(animalT)
  pet.addImplement(familiar)
  pet.isAbstract(True)
  friendliness = ast.Type("Friendliness")
  friendlinessA = ast.Attr("friendliness",friendliness,publ)
  pet.addMethod(cares)
  pet.addAttribute(friendlinessA)

  wildFile = ast.File("Wild")
  wildNamespace = ast.Namespace("Wild")
  wildFile.addNamespace(wildNamespace)
  rep.addFile(wildFile)  
  wild = ast.Cl("Wild")
  wildNamespace.addClass(wild)
  usingBite = ast.Using("Bite")
  wildNamespace.addUsing(usingBite)
  wild.setExtend(animalT)
  biteT = ast.Type("Bite")
  wild.addImplement(biteT)
  wild.isAbstract(True)
  wildness = ast.Type("Wildness")
  wildnessA = ast.Attr("wildness",wildness,publ)
  wild.addAttribute(wildnessA)
  wild.addMethod(attack)

  dogFile = ast.File("Dog")
  rep.addFile(dogFile)
  usingPet = ast.Using("Pet")
  dogFile.addUsing(usingPet)
  dog = ast.Cl("Dog")
  dogFile.addClass(dog)
  petT= ast.Type("Pet")
  dog.setExtend(petT)
  caresImpl = ast.Method("cares",void,intrn)
  dog.addMethod(caresImpl)
  huntCat = ast.Method("huntCat", void, prot)
  catT = ast.Type("Cat")
  catP = ast.Parameter(catT,"cat")
  huntCat.addParameter(catP)
  energyT = ast.Type("Energy")
  energyP = ast.Parameter(energyT,"energy")
  huntCat.addParameter(energyP)
  dog.addMethod(huntCat)

  catFile = ast.File("Cat")
  rep.addFile(catFile)
  usingPetC = ast.Using("Pet")
  catFile.addUsing(usingPetC)
  cat = ast.Cl("Cat")
  catFile.addClass(cat)
  cat.setExtend(petT)
  cat.addMethod(caresImpl)
  mouw = ast.Method("mouw",void,prot)
  cat.addMethod(mouw)

  cowFile = ast.File("Cow")
  rep.addFile(cowFile)
  usingPetCow = ast.Using("Pet")
  cowFile.addUsing(usingPetCow)  
  cow = ast.Cl("Cow")
  cowFile.addClass(cow)
  cow.setExtend(petT)
  milk = ast.Type("Milk")
  milkA = ast.Attr("milk",milk,intrn)
  cow.addAttribute(milkA)
  cow.addMethod(caresImpl)
  giveMilk = ast.Method("giveMilk",milk,publ)
  cow.addMethod(giveMilk)

  tigerFile = ast.File("Tiger")
  rep.addFile(tigerFile)
  usingWild = ast.Using("Wild")
  tigerFile.addUsing(usingWild)
  tiger = ast.Cl("Tiger")
  tigerFile.addClass(tiger)
  wildT = ast.Type("Wild")
  tiger.setExtend(wildT)
  stripe = ast.Type("Stripe")
  stripeA = ast.Attr("stripe",stripe,prot)
  tiger.addAttribute(stripeA)
  attackImpl = ast.Method("attack",hurt,prot)
  tiger.addMethod(attackImpl)

  lionFile = ast.File("Lion")
  rep.addFile(lionFile)
  lionFile.addUsing(usingWild)
  lion = ast.Cl("Lion")
  lionFile.addClass(lion)
  lion.setExtend(wild)
  mane = ast.Type("Mane")
  maneA = ast.Attr("mane",mane,prot)
  lion.addAttribute(maneA)
  lion.addMethod(attackImpl)

def createSampleV1(rep):
  #rep = Representation()
  intrn = AccessModifier()
  publ = AccessModifier()
  publ.setPublic()
  priv = AccessModifier()
  priv.setPrivate()
  prot = AccessModifier()
  prot.setProtected()
  void = Type("Void")
  
  breath = Iface("Breath")
  lungs = Type("Lungs")
  lungsA = Attr("lungs",lungs,priv)
  breath.addAttribute(lungsA)
  respire=Method("respire",void,priv)
  breath.addMethod(respire)
  rep.addInterface(breath)
  eat = Iface("Eat")
  mouth = Type("Mouth")
  mouthA = Attr("mouth",mouth,prot)
  energy = Type("Energy")
  consume = Method("consume",energy,priv)
  meal = Type("Meal")
  food=Parameter(meal,"food")
  consume.addParameter(food)
  eat.addMethod(consume)
  eat.addAttribute(mouthA)
  rep.addInterface(eat)
  
  live = Iface("Live")
  live.addExtend(breath)
  live.addExtend(eat)
  body = Type("Body")
  bodyA = Attr("body",body,prot)
  eat.addAttribute(bodyA)
  exist=Method("exist",void,priv)
  live.addMethod(exist)
  rep.addInterface(live)
  
  bite = Iface("Bite")
  teeth = Type("Teeth")
  teethA = Attr("teeth",teeth,priv)
  bite.addAttribute(teethA)
  hurt = Type("Hurt")
  attack=Method("attack",hurt,prot)
  attack.isAbstract(True)
  bite.addMethod(attack)
  rep.addInterface(bite)
  familiar = Iface("Familiar")
  cares = Method("cares",void,intrn)
  cares.isAbstract(True)
  familiar.addMethod(cares)
  rep.addInterface(familiar)
  
  animal = Cl("Animal")
  bone = Type("Bone")
  boneA = Attr("bone",bone,publ)
  animal.addAttribute(boneA)
  animal.addImplement(live)
  move = Method("move",void,prot)
  animal.addMethod(move)
  animal.isAbstract(True)
  rep.addClass(animal)
  
  
  pet = Cl("Pet")
  pet.setExtend(animal)
  pet.addImplement(familiar)
  pet.isAbstract(True)
  friendliness = Type("Friendliness")
  friendlinessA = Attr("friendliness",friendliness,publ)
  pet.addMethod(cares)
  pet.addAttribute(friendlinessA)
  rep.addClass(pet)
  
  wild = Cl("Wild")
  wild.setExtend(animal)
  wild.addImplement(bite)
  wild.isAbstract(True)
  wildness = Type("Wildness")
  wildnessA = Attr("wildness",wildness,publ)
  wild.addAttribute(wildnessA)
  wild.addMethod(attack)
  rep.addClass(wild)
  
  dog = Cl("Dog")
  dog.setExtend(pet)
  caresImpl = Method("cares",void,intrn)
  dog.addMethod(caresImpl)
  huntCat = Method("huntCat", void, prot)
  catT = Type("Cat")
  catP=Parameter(catT,"cat")
  huntCat.addParameter(catP)
  energyT = Type("Energy")
  energyP=Parameter(energyT,"energy")
  huntCat.addParameter(energyP)
  dog.addMethod(huntCat)
  rep.addClass(dog)
  
  cat = Cl("Cat")
  cat.setExtend(pet)
  cat.addMethod(caresImpl)
  mouw = Method("mouw",void,prot)
  cat.addMethod(mouw)
  rep.addClass(cat)
  
  cow = Cl("Cow")
  cow.setExtend(pet)
  milk = Type("Milk")
  milkA = Attr("milk",milk,intrn)
  cow.addAttribute(milkA)
  cow.addMethod(caresImpl)
  giveMilk = Method("giveMilk",milk,publ)
  cow.addMethod(giveMilk)
  rep.addClass(cow)
  
  tiger = Cl("Tiger")
  tiger.setExtend(wild)
  stripe = Type("Stripe")
  stripeA = Attr("stripe",stripe,prot)
  tiger.addAttribute(stripeA)
  attackImpl = Method("attack",hurt,prot)
  tiger.addMethod(attackImpl)
  rep.addClass(tiger)
  
  lion = Cl("Lion")
  lion.setExtend(wild)
  mane = Type("Mane")
  maneA = Attr("mane",mane,prot)
  lion.addAttribute(maneA)
  lion.addMethod(attackImpl)
  rep.addClass(lion)
