//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CommunicationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommunicationServiceReference.ICommunication", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ICommunication {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetContractsOfManager", ReplyAction="http://tempuri.org/ICommunication/GetContractsOfManagerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetContractsOfManagerPermissionDeniedForUserFau" +
            "lt", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetContractsOfManagerNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Contract[] GetContractsOfManager(PersistenceLayer.Dto.User manager);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/SetContract", ReplyAction="http://tempuri.org/ICommunication/SetContractResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/SetContractNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/SetContractPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void SetContract(PersistenceLayer.Dto.Contract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/SetHourlyRate", ReplyAction="http://tempuri.org/ICommunication/SetHourlyRateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/SetHourlyRatePermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/SetHourlyRateNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void SetHourlyRate(PersistenceLayer.Dto.EmployeeDescription employeeDescription, double hourlyRate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/RemoveContract", ReplyAction="http://tempuri.org/ICommunication/RemoveContractResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/RemoveContractNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/RemoveContractPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void RemoveContract(PersistenceLayer.Dto.Contract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetSummariesOfEmployee", ReplyAction="http://tempuri.org/ICommunication/GetSummariesOfEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetSummariesOfEmployeeNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetSummariesOfEmployeePermissionDeniedForUserFa" +
            "ult", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Summary[] GetSummariesOfEmployee(PersistenceLayer.Dto.EmployeeDescription employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetLastSummaries", ReplyAction="http://tempuri.org/ICommunication/GetLastSummariesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetLastSummariesPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetLastSummariesNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Summary[] GetLastSummaries(PersistenceLayer.Dto.EmployeeDescription employee, int ammount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetRecordsOfEmployeeBonuses", ReplyAction="http://tempuri.org/ICommunication/GetRecordsOfEmployeeBonusesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetRecordsOfEmployeeBonusesPermissionDeniedForU" +
            "serFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetRecordsOfEmployeeBonusesNoActiveSessionFault" +
            "", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.WorkRecord[] GetRecordsOfEmployeeBonuses(PersistenceLayer.Dto.EmployeeDescription employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetRecordsOfEmployeeNonBonuses", ReplyAction="http://tempuri.org/ICommunication/GetRecordsOfEmployeeNonBonusesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetRecordsOfEmployeeNonBonusesPermissionDeniedF" +
            "orUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetRecordsOfEmployeeNonBonusesNoActiveSessionFa" +
            "ult", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.WorkRecord[] GetRecordsOfEmployeeNonBonuses(PersistenceLayer.Dto.EmployeeDescription employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetContractOfManagerWithUser", ReplyAction="http://tempuri.org/ICommunication/GetContractOfManagerWithUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetContractOfManagerWithUserPermissionDeniedFor" +
            "UserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetContractOfManagerWithUserNoActiveSessionFaul" +
            "t", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Contract[] GetContractOfManagerWithUser(PersistenceLayer.Dto.PublicUserInfo manager);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetContractOfManagerWithProject", ReplyAction="http://tempuri.org/ICommunication/GetContractOfManagerWithProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetContractOfManagerWithProjectPermissionDenied" +
            "ForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetContractOfManagerWithProjectNoActiveSessionF" +
            "ault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Contract[] GetContractOfManagerWithProject(PersistenceLayer.Dto.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/Login", ReplyAction="http://tempuri.org/ICommunication/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/LoginNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/LoginPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        bool Login(string user, string passwd, PersistenceLayer.Dto.Role[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/MultiLogin", ReplyAction="http://tempuri.org/ICommunication/MultiLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/MultiLoginPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/MultiLoginNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Role[] MultiLogin(string user, string passwd, PersistenceLayer.Dto.Role[] roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/Logout", ReplyAction="http://tempuri.org/ICommunication/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/LogoutPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/LogoutNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        bool Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/ChangeMyPassword", ReplyAction="http://tempuri.org/ICommunication/ChangeMyPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.IncorrectOldPassword), Action="http://tempuri.org/ICommunication/ChangeMyPasswordIncorrectOldPasswordFault", Name="IncorrectOldPassword", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/ChangeMyPasswordNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void ChangeMyPassword(string oldPasswordHash, string newPasswordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetUsers", ReplyAction="http://tempuri.org/ICommunication/GetUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetUsersNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetUsersPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetProjects", ReplyAction="http://tempuri.org/ICommunication/GetProjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetProjectsPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetProjectsNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Project[] GetProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetEmployeesDescriptions", ReplyAction="http://tempuri.org/ICommunication/GetEmployeesDescriptionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetEmployeesDescriptionsPermissionDeniedForUser" +
            "Fault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetEmployeesDescriptionsNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.EmployeeDescription[] GetEmployeesDescriptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/SetUser", ReplyAction="http://tempuri.org/ICommunication/SetUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/SetUserPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/SetUserNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void SetUser(PersistenceLayer.Dto.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/SetPassword", ReplyAction="http://tempuri.org/ICommunication/SetPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/SetPasswordNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/SetPasswordPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void SetPassword(string login, string newPasswordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/SetProject", ReplyAction="http://tempuri.org/ICommunication/SetProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/SetProjectPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/SetProjectNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void SetProject(PersistenceLayer.Dto.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/SetEmployeeDescription", ReplyAction="http://tempuri.org/ICommunication/SetEmployeeDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/SetEmployeeDescriptionPermissionDeniedForUserFa" +
            "ult", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/SetEmployeeDescriptionNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void SetEmployeeDescription(PersistenceLayer.Dto.EmployeeDescription employeeDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/RemoveUser", ReplyAction="http://tempuri.org/ICommunication/RemoveUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/RemoveUserPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/RemoveUserNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void RemoveUser(PersistenceLayer.Dto.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/RemoveProject", ReplyAction="http://tempuri.org/ICommunication/RemoveProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/RemoveProjectNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/RemoveProjectPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void RemoveProject(PersistenceLayer.Dto.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/RemoveEmployeeDescription", ReplyAction="http://tempuri.org/ICommunication/RemoveEmployeeDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/RemoveEmployeeDescriptionPermissionDeniedForUse" +
            "rFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/RemoveEmployeeDescriptionNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void RemoveEmployeeDescription(PersistenceLayer.Dto.EmployeeDescription employeeDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetUserInfo", ReplyAction="http://tempuri.org/ICommunication/GetUserInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetUserInfoNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetUserInfoPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.User GetUserInfo(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetEmployeeDescriptions", ReplyAction="http://tempuri.org/ICommunication/GetEmployeeDescriptionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetEmployeeDescriptionsPermissionDeniedForUserF" +
            "ault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetEmployeeDescriptionsNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.EmployeeDescription[] GetEmployeeDescriptions(PersistenceLayer.Dto.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetContracts", ReplyAction="http://tempuri.org/ICommunication/GetContractsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetContractsPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetContractsNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Contract[] GetContracts(PersistenceLayer.Dto.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetRecords", ReplyAction="http://tempuri.org/ICommunication/GetRecordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetRecordsPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetRecordsNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.WorkRecord[] GetRecords(PersistenceLayer.Dto.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/SetRecord", ReplyAction="http://tempuri.org/ICommunication/SetRecordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/SetRecordNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/SetRecordPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void SetRecord(PersistenceLayer.Dto.WorkRecord record);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/SetSummary", ReplyAction="http://tempuri.org/ICommunication/SetSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/SetSummaryPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/SetSummaryNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void SetSummary(PersistenceLayer.Dto.Summary summary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/RemoveRecord", ReplyAction="http://tempuri.org/ICommunication/RemoveRecordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/RemoveRecordNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/RemoveRecordPermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        void RemoveRecord(PersistenceLayer.Dto.WorkRecord record);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetPaymentHistoryRange", ReplyAction="http://tempuri.org/ICommunication/GetPaymentHistoryRangeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetPaymentHistoryRangeNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetPaymentHistoryRangePermissionDeniedForUserFa" +
            "ult", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        System.DateTime GetPaymentHistoryRange(PersistenceLayer.Dto.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetWorkHistoryRange", ReplyAction="http://tempuri.org/ICommunication/GetWorkHistoryRangeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetWorkHistoryRangeNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetWorkHistoryRangePermissionDeniedForUserFault" +
            "", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        System.DateTime GetWorkHistoryRange(PersistenceLayer.Dto.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetRecordsByDate", ReplyAction="http://tempuri.org/ICommunication/GetRecordsByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetRecordsByDateNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetRecordsByDatePermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.WorkRecord[] GetRecordsByDate(PersistenceLayer.Dto.User user, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetContractsByDate", ReplyAction="http://tempuri.org/ICommunication/GetContractsByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetContractsByDateNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetContractsByDatePermissionDeniedForUserFault", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Contract[] GetContractsByDate(PersistenceLayer.Dto.User user, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetProjecsOfManager", ReplyAction="http://tempuri.org/ICommunication/GetProjecsOfManagerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetProjecsOfManagerNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetProjecsOfManagerPermissionDeniedForUserFault" +
            "", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.Project[] GetProjecsOfManager(PersistenceLayer.Dto.User manager);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetEmployeesOfProject", ReplyAction="http://tempuri.org/ICommunication/GetEmployeesOfProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetEmployeesOfProjectPermissionDeniedForUserFau" +
            "lt", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetEmployeesOfProjectNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.EmployeeDescription[] GetEmployeesOfProject(PersistenceLayer.Dto.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunication/GetRecordsOfEmployee", ReplyAction="http://tempuri.org/ICommunication/GetRecordsOfEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.NoActiveSession), Action="http://tempuri.org/ICommunication/GetRecordsOfEmployeeNoActiveSessionFault", Name="NoActiveSession", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(Server.Shared.Exceptions.PermissionDeniedForUser), Action="http://tempuri.org/ICommunication/GetRecordsOfEmployeePermissionDeniedForUserFaul" +
            "t", Name="PermissionDeniedForUser", Namespace="http://schemas.datacontract.org/2004/07/Server.Shared.Exceptions")]
        PersistenceLayer.Dto.WorkRecord[] GetRecordsOfEmployee(PersistenceLayer.Dto.EmployeeDescription employeeDesc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommunicationChannel : Client.CommunicationServiceReference.ICommunication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommunicationClient : System.ServiceModel.ClientBase<Client.CommunicationServiceReference.ICommunication>, Client.CommunicationServiceReference.ICommunication {
        
        public CommunicationClient() {
        }
        
        public CommunicationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommunicationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PersistenceLayer.Dto.Contract[] GetContractsOfManager(PersistenceLayer.Dto.User manager) {
            return base.Channel.GetContractsOfManager(manager);
        }
        
        public void SetContract(PersistenceLayer.Dto.Contract contract) {
            base.Channel.SetContract(contract);
        }
        
        public void SetHourlyRate(PersistenceLayer.Dto.EmployeeDescription employeeDescription, double hourlyRate) {
            base.Channel.SetHourlyRate(employeeDescription, hourlyRate);
        }
        
        public void RemoveContract(PersistenceLayer.Dto.Contract contract) {
            base.Channel.RemoveContract(contract);
        }
        
        public PersistenceLayer.Dto.Summary[] GetSummariesOfEmployee(PersistenceLayer.Dto.EmployeeDescription employee) {
            return base.Channel.GetSummariesOfEmployee(employee);
        }
        
        public PersistenceLayer.Dto.Summary[] GetLastSummaries(PersistenceLayer.Dto.EmployeeDescription employee, int ammount) {
            return base.Channel.GetLastSummaries(employee, ammount);
        }
        
        public PersistenceLayer.Dto.WorkRecord[] GetRecordsOfEmployeeBonuses(PersistenceLayer.Dto.EmployeeDescription employee) {
            return base.Channel.GetRecordsOfEmployeeBonuses(employee);
        }
        
        public PersistenceLayer.Dto.WorkRecord[] GetRecordsOfEmployeeNonBonuses(PersistenceLayer.Dto.EmployeeDescription employee) {
            return base.Channel.GetRecordsOfEmployeeNonBonuses(employee);
        }
        
        public PersistenceLayer.Dto.Contract[] GetContractOfManagerWithUser(PersistenceLayer.Dto.PublicUserInfo manager) {
            return base.Channel.GetContractOfManagerWithUser(manager);
        }
        
        public PersistenceLayer.Dto.Contract[] GetContractOfManagerWithProject(PersistenceLayer.Dto.Project project) {
            return base.Channel.GetContractOfManagerWithProject(project);
        }
        
        public bool Login(string user, string passwd, PersistenceLayer.Dto.Role[] roles) {
            return base.Channel.Login(user, passwd, roles);
        }
        
        public PersistenceLayer.Dto.Role[] MultiLogin(string user, string passwd, PersistenceLayer.Dto.Role[] roles) {
            return base.Channel.MultiLogin(user, passwd, roles);
        }
        
        public bool Logout() {
            return base.Channel.Logout();
        }
        
        public void ChangeMyPassword(string oldPasswordHash, string newPasswordHash) {
            base.Channel.ChangeMyPassword(oldPasswordHash, newPasswordHash);
        }
        
        public PersistenceLayer.Dto.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public PersistenceLayer.Dto.Project[] GetProjects() {
            return base.Channel.GetProjects();
        }
        
        public PersistenceLayer.Dto.EmployeeDescription[] GetEmployeesDescriptions() {
            return base.Channel.GetEmployeesDescriptions();
        }
        
        public void SetUser(PersistenceLayer.Dto.User user) {
            base.Channel.SetUser(user);
        }
        
        public void SetPassword(string login, string newPasswordHash) {
            base.Channel.SetPassword(login, newPasswordHash);
        }
        
        public void SetProject(PersistenceLayer.Dto.Project project) {
            base.Channel.SetProject(project);
        }
        
        public void SetEmployeeDescription(PersistenceLayer.Dto.EmployeeDescription employeeDescription) {
            base.Channel.SetEmployeeDescription(employeeDescription);
        }
        
        public void RemoveUser(PersistenceLayer.Dto.User user) {
            base.Channel.RemoveUser(user);
        }
        
        public void RemoveProject(PersistenceLayer.Dto.Project project) {
            base.Channel.RemoveProject(project);
        }
        
        public void RemoveEmployeeDescription(PersistenceLayer.Dto.EmployeeDescription employeeDescription) {
            base.Channel.RemoveEmployeeDescription(employeeDescription);
        }
        
        public PersistenceLayer.Dto.User GetUserInfo(string login) {
            return base.Channel.GetUserInfo(login);
        }
        
        public PersistenceLayer.Dto.EmployeeDescription[] GetEmployeeDescriptions(PersistenceLayer.Dto.User user) {
            return base.Channel.GetEmployeeDescriptions(user);
        }
        
        public PersistenceLayer.Dto.Contract[] GetContracts(PersistenceLayer.Dto.User user) {
            return base.Channel.GetContracts(user);
        }
        
        public PersistenceLayer.Dto.WorkRecord[] GetRecords(PersistenceLayer.Dto.User user) {
            return base.Channel.GetRecords(user);
        }
        
        public void SetRecord(PersistenceLayer.Dto.WorkRecord record) {
            base.Channel.SetRecord(record);
        }
        
        public void SetSummary(PersistenceLayer.Dto.Summary summary) {
            base.Channel.SetSummary(summary);
        }
        
        public void RemoveRecord(PersistenceLayer.Dto.WorkRecord record) {
            base.Channel.RemoveRecord(record);
        }
        
        public System.DateTime GetPaymentHistoryRange(PersistenceLayer.Dto.User user) {
            return base.Channel.GetPaymentHistoryRange(user);
        }
        
        public System.DateTime GetWorkHistoryRange(PersistenceLayer.Dto.User user) {
            return base.Channel.GetWorkHistoryRange(user);
        }
        
        public PersistenceLayer.Dto.WorkRecord[] GetRecordsByDate(PersistenceLayer.Dto.User user, System.DateTime dt) {
            return base.Channel.GetRecordsByDate(user, dt);
        }
        
        public PersistenceLayer.Dto.Contract[] GetContractsByDate(PersistenceLayer.Dto.User user, System.DateTime dt) {
            return base.Channel.GetContractsByDate(user, dt);
        }
        
        public PersistenceLayer.Dto.Project[] GetProjecsOfManager(PersistenceLayer.Dto.User manager) {
            return base.Channel.GetProjecsOfManager(manager);
        }
        
        public PersistenceLayer.Dto.EmployeeDescription[] GetEmployeesOfProject(PersistenceLayer.Dto.Project project) {
            return base.Channel.GetEmployeesOfProject(project);
        }
        
        public PersistenceLayer.Dto.WorkRecord[] GetRecordsOfEmployee(PersistenceLayer.Dto.EmployeeDescription employeeDesc) {
            return base.Channel.GetRecordsOfEmployee(employeeDesc);
        }
    }
}
